[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings=['@OpenZeppelin/openzeppelin-contracts=lib/openzeppelin-contracts',
'@chainlink=lib/chainlink-evm',
'@chainlink-ccip=lib/chainlink-ccip']

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
